# Generated by Django 2.0.6 on 2018-07-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPA_System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='CSU_Position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Cell_Component_Leader_Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Cell_Leader_Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Tissue_Leader_Name',
        ),
    ]
