# Generated by Django 2.0.6 on 2018-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPA_System', '0002_auto_20180725_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CSU_Position',
            field=models.CharField(choices=[('None', 'None'), ('CCL', 'Cell Component Leader'), ('CL', 'Cell Leader'), ('TL', 'Tissue Leader')], default='None', max_length=4),
        ),
    ]
