# Generated by Django 2.0.6 on 2018-07-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPA_System', '0003_user_csu_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cell_Component_Leader_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Cell_Leader_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Tissue_Leader_Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
